/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Name of package */
#define PACKAGE "njudge"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""njudge""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""njudge" 1.2.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "-njudge-"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.2.0"

/* Version number of package */
#define VERSION "1.2.0"
