#! /bin/sh
#
# This file is to be used when the JK wants to move the game directories
# to a sub directory
#
# Be sure to change the references to "games" below to match the value of
# GAME_DIR in dip.conf


mkdir games
ls -d D* | sed 's/^D//' | awk '{print "mv D" $1 " games/" $1}' | /bin/sh
