#!/bin/sh
#
#  Increment the major or minor version number.
#
MYHOST=`hostname|sed 's/\..*$//'`
awk '
  BEGIN { 
    FS = "	"; 
    myhost = "'$MYHOST'"; 
  }
  $2 == "VERMAJ" { vermaj = $3 }
  $2 == "VERMIN" { vermin = $3 }
  $2 == "HOST"   { host   = $3 }
  $2 == "FROM"   { from   = $3 }
  $1 != "#define"
  END { 
    host = substr(host,2,length(host)-2);
    from = substr(from,2,length(from)-2);
    if (myhost != host) {
      from = " (from " host " " vermaj "." vermin from ")";
      vermaj = 1; vermin = 0
    } else {
      if ("'$1'" == "VERMAJ") {
        vermaj++; vermin = 0
      } else {
        vermin++
      }
    }
    print "#define	VERMAJ	" vermaj
    print "#define	VERMIN	" vermin
    print "#define	HOST	\"" myhost "\""
    print "#define	FROM	\"" from "\""
    print "Version " vermaj "." vermin " " myhost >"tmp_x1"
  }
' version.h > tmp_x2
mv tmp_x2 version.h
echo " " >> log
echo `cat tmp_x1` "($USER)" `date` >> log
rm tmp_x1
