#!/bin/csh
# /bin/sh  (Note: /bin/sh fails to work if N files are open)
#
#  Invoked as smail file subject address
#
setenv FROM test_judge
# FROM=u.washington.edu export FROM
date >>mail.log
echo "===== mail sent to $3/$2" >>mail.log
/usr/bin/head -10 $1 >>mail.log
cat dip.msg $1 > dip.reply1
/bin/mail -s "$2" <dip.reply1 $3
rm -f dip.reply1
rm -f dip.xfail
