#!/bin/csh
# /bin/sh  (Note: /bin/sh fails to work if N files are open)
#
#  Invoked as smail file subject address
#
setenv FROM eff.org
# FROM=u.washington.edu export FROM
date >>mail.log
echo "===== mail sent to $3/$2" >>mail.log
/usr/ucb/head -10 $1 >>mail.log
cat dip.msg $1 > /tmp/dip.reply
/usr/ucb/mail -s "$2" </tmp/dip.reply $3
rm -f /tmp/dip.reply
rm -f dip.xfail
