#!/usr/bin/perl -w
use strict;

my $destdir='/home/judge';
my $arg = "";
my $answer = "";

$arg = shift;
if ($arg eq "purge")
{
  my @fields = stat($destdir);
  my $user = (getpwuid($fields[4]));
  my $group =  scalar(getgrgid($fields[5]));
  print "Remove user $user, group $group, and $destdir from the system? [y/n]\n";
  $answer = <stdin>;
  if ($answer =~ /^[yY]/)
  {
    `userdel -r $user`;
  } 
  qx/rm -rf $destdir/;
}


